### ISSUE TITLE
./tuning-primer.sh display error No valid socket file found!

### ISSUE THREAD

**Issue by tehseenkn** [BMDan/tuning-primer.sh#2]
I am running tuning-primer.sh script on cygwin following error occurs.

No valid socket file "" found!
The mysqld process is not running or it is installed in a custom location.
If you are sure mysqld is running, execute script in "prompt" mode or set
the socket= variable at the top of this script

I also run it in prompt mod provide socket file directory path /tmp/mysql.sock still above error is occurring.

any solution?.

**Comment by BMDan** [comment]
This was almost certainly caused by /tmp/mysql.sock not being a socket, but the error handling around that was pretty obtuse.  After https://github.com/BMDan/tuning-primer.sh/commit/353a32d390d41284005d1bd79f07765d4808ab98, we now very explicitly tell you what's wrong:

```
$ ./tuning-primer.sh prompt
Username [anonymous] :
Password [<none>] :

Socket [ /var/lib/mysql/mysql.sock ] : /lol/wat.sock
No valid socket file at '/lol/wat.sock'!
You've explicitly specified a socket location, but that location either
doesn't exist, or isn't a socket.
```

whereas before, we'd do:
```
$ ./tuning-primer.sh prompt
Username [anonymous] :
Password [<none>] :

Socket [ /var/lib/mysql/mysql.sock ] : /lol/wat.sock
No valid socket file "/lol/wat.sock" found!
The mysqld process is not running or it is installed in a custom location.
If you are sure mysqld is running, execute script in "prompt" mode or set
the socket= variable at the top of this script
```
which was indistinguishable from the case where you hadn't specified a socket at all.  This was especially confusing for people who e.g. have the socket in the default location, but who don't have `rx` permissions on the directory containing it, causing `[ -S` to fail.
